server:
  port: 8888
spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          search-locations: file://C:\work\springcloud\git-local-repo
        git:
          uri: https://github.com/mjjunng/spring-cloud-config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
