server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: user-service    #register user-service's forwarding
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: catalog-service    #register catalog-service's forwarding
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: first-service   # routing id
#          uri: http://localhost:8081/  # 2. output path
          uri: lb://MY-FIRST-SERVICE    # output path registered eureka server
          predicates:
            - Path=/first-service/**    # 1. input path
          filters:    # register custom filter
            - CustomFilter
        - id: second-service
#          uri: http://localhost:8082/
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true
      default-filters:  # register global filter
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Golbal Filter
            preLogger: true
            postLogger: true


